fix: dates sent as ISO
collective/volto-form-block pull request #122
Opened 2024-12-06 11:52 UTC by mamico

dates should be sent in ISO format (the widget's default should be fine), not DD-MM-YYYY

2024-12-06 12:00 UTC, JeffersonBledsoe commented
@mamico This needs [collective.volto.formsupport](https://github.com/collective/collective.volto.formsupport/blob/main/CHANGES.rst#314-2024-09-27) >= 3.1.4 (specifically https://github.com/collective/collective.volto.formsupport/pull/34) to work right? What happens if the backend is less than this version?

2024-12-06 12:05 UTC, mamico commented
> @mamico This needs [collective.volto.formsupport](https://github.com/collective/collective.volto.formsupport/blob/main/CHANGES.rst#314-2024-09-27) >= 3.1.4 (specifically [collective/collective.volto.formsupport#34](https://github.com/collective/collective.volto.formsupport/pull/34)) to work right? What happens if the backend is less than this version?

In this case, I believe dates would be saved/sent in ISO format instead of DD/MM/YYYY format.

2025-01-08 23:15 UTC, JeffersonBledsoe commented
> In this case, I believe dates would be saved/sent in ISO format instead of DD/MM/YYYY format.

@mamico This is a breaking change then, right? Otherwise, LGTM!

2025-02-09 10:15 UTC, stevepiercy requested changes

2025-02-09 10:15 UTC, stevepiercy commented on src/components/View.jsx
> +
Please delete the commented obsolete code.

2025-02-13 18:20 UTC, mamico commented
> > In this case, I believe dates would be saved/sent in ISO format instead of DD/MM/YYYY format.
> 
> @mamico This is a breaking change then, right? Otherwise, LGTM!

Not sure if we can call it breaking, but we can document the backend requirement in the README, as we've done for the others.

2025-02-13 21:18 UTC, mamico commented on src/components/View.jsx
> +
done

2025-02-13 21:28 UTC, stevepiercy requested changes
I'll push these commits. This will make it easier to read and maintain.

2025-02-13 21:28 UTC, stevepiercy commented on README.md
> +> **Note**: Since version v3.11.0 of this adddon, it's required it's required [collective.volto.formsupport](https://github.com/collective/collective.volto.formsupport) 3.1.4 or higher.
```suggestion
> - Since version v3.11.0 of this add-on, [`collective.volto.formsupport`](https://github.com/collective/collective.volto.formsupport) 3.1.4 or later is required.
```

2025-02-13 21:28 UTC, stevepiercy commented on README.md
>  > **Note**: Since version v3.0.0 of this addon, it's required Volto >= 16.0.0-alpha.38
```suggestion
> - Since version v3.0.0 of this add-on, Volto 16.0.0-alpha.38 or later is required.
```

2025-02-13 21:28 UTC, stevepiercy commented on README.md
>  > **Note**: Since version v2.1.2 of this addon, it's required Volto 14.2.0
```suggestion
> - Since version v2.1.2 of this add-on, Volto 14.2.0 or later is required.
```

2025-02-13 21:29 UTC, stevepiercy approved these changes

2025-02-13 21:31 UTC, stevepiercy commented
Here's how the changes I made will look.

> [!NOTE]
> - Since version v2.0.0 of this add-on, [`collective.volto.formsupport`](https://github.com/collective/collective.volto.formsupport) 2.0.0 or later and performing its upgrade steps is required.
> - Since version v2.1.2 of this add-on, Volto 14.2.0 or later is required.
> - Since version v3.0.0 of this add-on, Volto 16.0.0-alpha.38 or later is required.
> - Since version v3.11.0 of this add-on, [`collective.volto.formsupport`](https://github.com/collective/collective.volto.formsupport) 3.1.4 or later is required.

2025-02-14 09:00 UTC, merged