feat: add static rich text field
collective/volto-form-block pull request #9
Opened 2021-08-12 09:31 UTC by nzambello

Adds a static rich text field (not a fillable field, just text to display between other fields, editable in the edit view, the opposite of other fields)

2021-08-12 12:30 UTC, tiberiuichim approved these changes

2021-08-12 14:53 UTC, pnicolli requested changes

2021-08-12 14:53 UTC, pnicolli commented on locales/it/LC_MESSAGES/volto.po
> +msgstr ""
You could add the italian translation as well, here

2021-08-12 15:54 UTC, pnicolli approved these changes
LGTM

2021-08-16 07:11 UTC, giuliaghisini approved these changes

2021-08-16 07:52 UTC, merged